language: android

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk7
  - oraclejdk8

script: "./gradlew assembleDebug"

env:
  global:
    secure: "PVbL8+paUZtJKEgWqq+Z73WZ00TKGJv26R1GDauhdoA8tMawYYy499JNFo6VUd0TSbYbPEvejJmS8d6V2fu5cnROrvweiiAsDoHOXXFIHPbQEzqE1cJqcIilsdR4YFP3SQ7Hv6SI/HVDxWkRAxgjvFjUSIGcnJqCAw/VffNlVhs="

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
